### ISSUE TITLE
RAD-Y1 - Cardinality of Patient Name & ID

### ISSUE THREAD

**Issue by lynnfel** [IHE/RAD.IMR#4]
**Section Number** Table 2:4.Y1.4.1.2.1-1: 

**Issue** The RAD-Y1 Bundle shall contain a Patient Resource.  The Patient Resource is currently unconstrained by IMR.  The cardinality for both Patient.identifier and Patient.name is 0..1 in FHIR.

The preface to the mapping table in RAD-Y1 says, "In radiology reports, there is a common set of values to be included. Table 2:4.Y1.4.1.2.1-1 specifies how the Sender shall map these attributes to FHIR DiagnosticReport Resource and other referenced resources."   I interpret that to mean that Patient Name and Patient ID are required to be mapped

**Proposed Change** Was this discussed already?

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by lynnfel** [comment]
This issue raises a real question, but you could also use it as a demo to RAD Tech on Friday to show how people can submit Github issues during Public Comment.   The text within the issue follows a template that is provided automatically when you start a new issue.

**Comment by kinsonho** [comment]
This was discussed. Basically what we are saying is that Patient is not radiology specific. So IMR does not impose any resource profile on it. Each deployment may impose deployment specific resource profiles on them. There is actually a subsection about this.

So the idea is that if you have patient name and patient ID, they should be mapped to the Patient resource as shown. However, the FHIR resource (as well as DICOM) keeps those attributes as optional because there are situations that they may not exist. IMR does not impose any further constraints on Patient.

This is why the table is informative, not normative, as commented in another issue.

**Comment by lynnfel** [comment]
your comment above says "they should be mapped to the patient resource".  But the text above the table sayes" Table 2:4.Y1.4.1.2.2.1-1 specifies how the Sender shall map these attributes to the IMR DiagnosticReport Resource and other referenced resources."   That seems to imply that the Report Creator shall update the Patient Resource with the name and ID it has, if necessary.

**Comment by kinsonho** [comment]
Discussed with Lynn. The Report Creator may actually create the patient as part of the report if the Patient resource does not exist yet in the FHIR server (the Patient may exist somewhere else, such as EMR already). This is because the FHIR server supporting IMR may be new and not have all the records backfilled yet.

No change.
