### ISSUE TITLE
RAD-Y1 - consider removing cardinality from mapping table

### ISSUE THREAD

**Issue by lynnfel** [IHE/RAD.IMR#5]
**Section Number** Table 2:4.Y1.4.1.2.2.1-1

**Issue** In the lynnfel-RAD-Y1-restructure branch, I have combined the 'required' and 'optional' mapping tables, per a suggestion from Kevin last week.  I agree that one mapping table is better.

When I combined the table, I added the cardinality column (because it existed in the previous 'optional' table and I did not want to delete information).

**Proposed Change** However, perhaps we should remove cardinality from the mapping table altogether, since the normative rqmts for that come from StructureDefinitions.  This would eliminate duplicate information.   If special instructions are needed on how to handle multiples, this could be included in the 'Notes' column.

**Priority**:

- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by lynnfel** [comment]
Kinson, if you agree to this, I can make the edit.

**Comment by kinsonho** [comment]
I added some comments inline with the review.

Also if the two lists combined and there is no cardinality column, then you don't know which one is required and which one is optional. If we do that, we need to make it clear that this is an informative table and the actual requirements are defined in the corresponding StructureDefinitions. This may or may not be clear to someone who is new to FHIR profiles because as Kevin mentioned, he would expect the text is the actual requirement while the StructureDefinition are the necessary artifacts for FHIR and it should match what is in the text.

Also I want to point out that my intention for the two tables is to highly the common attributes / sections available in a radiology report and where they are mapped to the IMR DiagnosticReport. So this gives the reader a sense of where the content mapping is. However, these two tables are not complete in the sense that there are additional required attributes defined in the StructureDefinition (e.g. category), as well as there are many more optional attributes which may be less relevant in radiology reporting. So just want to make sure that there is no confusion the content here are informative rather than normative, just to bridge the gap that someone may not be interested to review the StructureDefinition (or may not be technical to know how to read them).

**Comment by kinsonho** [comment]
Discussed with Lynn. Agree to keep the two tables separate but remove the cardinality in the second table.
